---
title: "tidyingAgeAndCourse"
author: "Darlene Erl Lapso"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r}
#getting the age average

age <- c(deets$Age)
```

```{r}
#converting age to numeric form

age <- as.numeric(gsub("[^0-9]", "", as.character(age)))
```

```{r}
#removes zeros

age <- as.numeric(gsub("0$", "", as.character(age)))
```

```{r}
#neglecting NAs in solving average
ave_age <- mean(age, na.rm = TRUE)

ave_age
```


```{r}
# removing decimals on ave_age
(ave_age <- floor(ave_age))
```

```{r}
#fills in the NAs with the ave_age
age[is.na(age)] <- ave_age
```

```{r}
# syncing to data
deets$Age <- age
```

```{r}
# graphs for age ( PIE CHART )

age_counts <- table(age)
percentages <- round(prop.table(age_counts) * 100, 1)
pie(age_counts, main = "Ages", labels = paste(names(age_counts), "\n", percentages, "%", sep = ""), col = rainbow(length(age_counts)), cex = 0.7)
legend("topright", legend = paste(names(age_counts), "-", percentages, "%", sep = ""), cex = 0.6, fill = rainbow(length(age_counts)))
```

```{r}
# ---------------------------------- Sex
```

```{r}
males <- subset(deets, Sex == "Male")
females <- subset(deets, Sex == "Female")

sex_counts <- data.frame(
  Sex = c("Male", "Female"),
  Count = c(nrow(males), nrow(females))
)

ggplot(sex_counts, aes(x = Sex, y = Count, fill = Sex)) +
  geom_bar(stat = "identity") +
  labs(title = "Distribution of Males and Females",
       x = "Sex",
       y = "Count") +
  scale_fill_manual(values = c("Male" = "skyblue", "Female" = "pink"))

```

```{r}
# ----------------------------------- Changing Courses to its acronym ----------

```

```{r}
# replacing long terms to acronyms

# show courses
print(deets$Course)

# to BSIT
to_bsit <- c(1, 14, 46, 56, 59, 61, 68)
deets$Course[to_bsit] <- "BSIT"

# to BSCE
to_bsce <- c(2)
deets$Course[to_bsce] <- "BSCE"

#to BS Agri
to_bsagri <- c(17, 40)
deets$Course[to_bsagri] <- "BS Agri"

# to BS Chem
to_bschem <- c(16, 80)
deets$Course[to_bschem] <- "BS Chem"

# to bsa
to_bsa <- c(25, 28)
deets$Course[to_bsa] <- "BSA"

# to bshm
to_bshm <- c(31, 98) 
deets$Course[to_bshm] <- "BSHM"

# to bs phar
to_bsphar <- c(44)
deets$Course[to_bsphar] <- "BS Phar"
```

```{r}
deets$Course
```

```{r}
# -------------------------------------- course -------------------------
```

```{r}
course <- deets$Course
```

```{r}
categorize_course <- function(course) {
  if (grepl("IT|CS|BSIT", course)) {
    return("Computer Literature")
  }
  else if (grepl("ED|BSED", course)) {
    return("Education")
  }
  else if (grepl("BSA|BSBA", course)) {
    return("Business and Finance")
  }
  else if (grepl("CE", course)) {
    return("Engineering")
  }
  else if (grepl("BSHM", course)) {
    return("Hospitality Management")
  }
  else {
    return("Other")
  }
}

course_categories <- sapply(course, categorize_course)
```

```{r}
# count the data of each category
category_counts <- table(course_categories)
```

```{r}
# convert the table to a data frame
category_counts_df <- as.data.frame(category_counts)
names(category_counts_df) <- c("Category", "Count")
```

```{r}
# create the bar plot
ggplot(category_counts_df, aes(x = Category, y = Count, fill = Category)) +
  geom_bar(stat = "identity") +
  labs(title = "Course Distribution by Category",
       x = "Category",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_fill_manual(values = c("Computer Literature" = "skyblue",
                               "Education" = "pink",
                               "Business and Finance" = "orange",
                               "Engineering" = "green",
                               "Hospitality Management" = "yellow",
                               "Other" = "grey"))

```
```{r}
# ----------------------------------- School --------------------------
```

```{r}
school <- deets$School

school_factor <- factor(School)

school_counts <- table(school_factor)

school_counts_df <- as.data.frame(school_counts)
names(school_counts_df) <- c("School", "Count")

```

```{r}
# Sort the data frame by Count in descending order
school_counts_df <- school_counts_df[order(-school_counts_df$Count), ]
```

```{r}
# Create the bar plot
ggplot(school_counts_df, aes(x = reorder(School, -Count), y = Count)) +
  geom_bar(stat = "identity", fill = "skyblue") +
  labs(title = "School Distribution",
       x = "School",
       y = "Count") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  coord_flip()

```

```{r}
# ------------------------------------ UTAUT conversion--------------------------- 

```

```{r}
#Read the excel file
questionnaire <- read_excel("questionnaire3g.xlsx", sheet = "Form Responses 1")
```

```{r}
conversion <- function(response) {
  if (response == "Strongly Disagree") {
    return(1)
  } else if (response == "Disagree") {
    return(2)
  } else if (response == "Neutral") {
    return(3)
  } else if (response == "Agree") {
    return(4)
  } else {
    return(5)
  }
}
```

```{r}
columns_to_convert <- c(10, 11, 12, 14, 17, 19, 20, 22, 23, 25, 26, 27, 28, 29, 30, 31, 32)

for (column_index in columns_to_convert) {
  questionnaire[[column_index]] <- sapply(questionnaire[[column_index]], conversion)
}
```

```{r}
conversion1 <- function(response) {
  if (is.na(response)) {
    return(NA)
  } else if (response == "Yes") {
    return(1)
  } else if (response == "No") {
    return(2)
  } else if (response == "Possibly") {
    return(3)
  } else {
    return(NA)
  }
}
```

```{r}
columns_to_convert1 <- c(9,15,16,18,21,24,33,34,35)

for (column in columns_to_convert1) {
  questionnaire[[column]] <- sapply(questionnaire[[column]], conversion1)
}
```

```{r}
# Calculate the mean and sd for Performance Expectancy
performanceExpectancy <- questionnaire[, c(9:11)]
```

```{r}
# getting the mean and sd
means1 <- colMeans(performanceExpectancy, na.rm = TRUE)
means1
sd_pe <- sapply(performanceExpectancy, sd, na.rm = TRUE)
sd_pe
```

```{r}
# getting the average
avg_mean1 <- round(mean(means1), 2)
avg_mean1
avg_sd1 <- round(mean(sd_pe), 2)
avg_sd1
```

```{r}
# calculate the mean and sd for Effort Expectancy
effortExpectancy <- questionnaire[, c(12:14)]
```

```{r}
# getting the mean and sd
means2 <- colMeans(effortExpectancy, na.rm = TRUE)
means2
sd_ee <- sapply(effortExpectancy, sd, na.rm = TRUE)
sd_ee
```

```{r}
# average
avg_mean2 <- round(mean(means2), 2)
avg_mean2
avg_sd2 <- round(mean(sd_ee), 2)
avg_sd2
```

```{r}
# Calculate the mean and sd for Social Influence
socialInfluence <- questionnaire[, c(19:21)]
```

```{r}
# getting the mean and sd
means3 <- colMeans(socialInfluence, na.rm = TRUE) 
means3
sd_si <- sapply(socialInfluence, sd, na.rm = TRUE)
sd_si
```

```{r}
# average
avg_mean3 <- round(mean(means3), 2)
avg_mean3
avg_sd3 <- round(mean(sd_si), 2)
avg_sd3
```

```{r}
# Calculate the mean and sd for Facilitating Conditions
facilitatingConditions <- questionnaire[, c(22:25)]
```

```{r}
# getting the mean and sd
means4 <- colMeans(facilitatingConditions, na.rm = TRUE)
means4
sd_fc <- sapply(facilitatingConditions, sd, na.rm = TRUE)
sd_fc
```

```{r}
avg_mean4 <- round(mean(means4), 2)
avg_mean4
avg_sd4 <- round(mean(sd_fc), 2)
avg_sd4
```

```{r}
# Calculate the mean and sd for Behavioral Intention to use the system
behavioralIntention <- questionnaire[, c(33:35)]
```

```{r}
# getting the mean and sd
means5 <- colMeans(behavioralIntention, na.rm = TRUE)
means5
sd_bi <- sapply(behavioralIntention, sd, na.rm = TRUE)
sd_bi

# average
avg_mean5 <- round(mean(means5), 2)
avg_mean5
avg_sd5 <- round(mean(sd_bi), 2)
avg_sd5
```

```{r}
#####Make a data frame of all factors######
pe <- data.frame(
  Description = "Performance Expectancy",
  Mean = means1,
  SD = sd_pe,
  Average_Mean = avg_mean1,
  Average_SD = avg_sd1
)
```

```{r}
ee <- data.frame(
  Description = "Effort Expectancy",
  Mean = means2,
  SD = sd_ee,
  Average_Mean = total_mean2,
  Average_SD = total_sd2
)
```

```{r}
si <- data.frame(
  Description = "Social Influence",
  Mean = means3,
  SD = sd_si,
  Average_Mean = total_mean3,
  Average_SD = total_sd3
)
```

```{r}
fc <- data.frame(
  Description = "Facilitating Conditions",
  Mean = means4,
  SD = sd_fc,
  Average_Mean = total_mean4,
  Average_SD = total_sd4
)
```

```{r}
bi <- data.frame(
  Description = "Behavioral Intention",
  Mean = means5,
  SD = sd_bi,
  Average_Mean = total_mean5,
  Average_SD = total_sd5
)
```

```{r}
summary <- rbind(pe, ee, si, fc, bi)
summary_table<-  kable(summary)
```


